//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salesman_Master()
        {
            this.Sales_Order = new HashSet<Sales_Order>();
        }
    
        public string SalesManNo { get; set; }
        public string SalesmanName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<decimal> PinCode { get; set; }
        public string State { get; set; }
        public decimal salamt { get; set; }
        public decimal tgttoget { get; set; }
        public decimal ytdsales { get; set; }
        public string remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order> Sales_Order { get; set; }
    }
}
